### ISSUE TITLE
Allow binding to socket files instead

### ISSUE THREAD

**Issue by BrainStone** [lucko/bytebin#3]
It would be really useful if it was possible that instead of an IP and port it could bind the socket to a unix socket file.

**Comment by joestr** [comment]
In what case that would be useful? Also this particular HTTP server requires a hostname and port combination to start so there is no way to bind to a unix socket.

**Comment by BrainStone** [comment]
I don't see where a hostname would be required.  
And the use would be the same case normal socket files have. Having a service in a reliable spot without blocking any IP and port.

**Comment by lucko** [comment]
Unfortunately as far as I can tell rapidoid doesn't support this.
